source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.yoomoney.ru/scm/sdk/cocoa-pod-specs.git'

platform :ios, '15.0'
use_frameworks!

target 'BBPlay' do

pod 'Alamofire'
pod 'SnapKit'
pod 'R.swift', '6.1.0'
pod 'Kingfisher'
pod 'SkeletonView'
pod 'NeedleFoundation'
pod 'AppMetricaAnalytics', '5.14.0'
pod 'AppMetricaPush', '~> 3.2.0'

pod 'FirebaseCore'
pod 'FirebaseAnalytics'
pod 'FirebaseCrashlytics'
pod 'FirebaseRemoteConfig'
pod 'FirebaseMessaging'

pod 'YooKassaPayments', :git => 'https://git.yoomoney.ru/scm/sdk/yookassa-payments-swift.git', :tag => '8.1.1'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
 end
end
